route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'Prakashsinha Bayas'
            channel: '#my-slack-alerts'
            api_url: 'https://hooks.slack.com/services/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'
